import { notFound, redirect } from "next/navigation";
import { getConcertById } from "@/lib/repositories/concerts";
import { getConcertArtists } from "@/lib/repositories/profiles";
import { createClient } from "@/lib/supabase/server";
import { ConcertFormCard } from "@/components/concert/ConcertFormCard";
import type { ConcertInput } from "@/lib/schemas/concert";
import { format } from "date-fns";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function EditConcertPage({ params }: PageProps) {
  const { id } = await params;
  const result = await getConcertById(id);
  if (!result.ok) notFound();

  const concert = result.data;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user || user.id !== concert.created_by) redirect("/");

  const [artists, profileRow] = await Promise.all([
    getConcertArtists(id),
    supabase.from("profiles").select("role").eq("id", user.id).single(),
  ]);

  const userRole = profileRow.data?.role ?? "USER";

  // Si el nombre fue auto-generado desde la sala (sin artistas), lo dejamos
  // vacío para que el formulario pueda re-generarlo al añadir artistas.
  const nameWasAutoGenerated = artists.length === 0 && concert.name === concert.venue_name;

  const defaultValues: Partial<ConcertInput> & {
    id: string;
    image_url?: string;
    artistIds?: string[];
    artistFreeNames?: string[];
  } = {
    id: concert.id,
    name: nameWasAutoGenerated ? "" : concert.name,
    description: concert.description ?? undefined,
    date_time: format(new Date(concert.date_time), "yyyy-MM-dd'T'HH:mm"),
    venue_name: concert.venue_name,
    venue_address: concert.venue_address ?? undefined,
    ticket_url: concert.ticket_url ?? undefined,
    price: concert.price !== null ? Number(concert.price) : undefined,
    visibility: concert.visibility ?? "PUBLIC",
    artistIds: artists.flatMap((a) => (a.kind === "registered" ? [a.id] : [])),
    artistFreeNames: artists.flatMap((a) => (a.kind === "unregistered" ? [a.name] : [])),
    ...(concert.image_url ? { image_url: concert.image_url } : {}),
  };

  return (
    <div className="mx-auto max-w-2xl px-4 py-10">
      <ConcertFormCard mode="edit" userRole={userRole} defaultValues={defaultValues} />
    </div>
  );
}
